language: ruby
rvm: 2.1
before_script:
- bundle exec jekyll build
after_success:
- "./_scripts/travis_deploy.sh"
branches:
  only:
  - master  # this is our preview branch
  - live    # this is our live site branch
notifications:
  slack: acs-stanford:nTs1cMbri1Nzrr6Qqt3r9opu
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up htmlproofer installation
addons:
    ssh_known_hosts:
    - 74.207.249.200
