name: Humanities + Design
markdown: redcarpet
highlighter: pygments
description: "We are a research lab at the Center for Spatial and Textual Analysis (CESTA), Stanford University."
url: "http://hdlab.stanford.edu"
port: 4000

