# Project or Lab name
name:                     "Crowdsourcing"
sub-name:                 "Crowdsourcing for the Humanities"
name:                     "Ockham"
sub-name:                 "A Platform for Research"
# is this a lab site or project site?
type:                     project
markdown:                 redcarpet
highlighter:              pygments
description:              "Ockham is a static site platform for quickly publishing collaborative research in the humanities."
category_dir :
category_title_prefix :   ''
category_title :          ''
google_id:                ''
disqus:                   ''
url:                      http://localhost:4000
permalink:                /:year/:month/:day/:title/
twitter:
#This is the base directory (cloud) where we share images
img-url:           "https://googledrive.com/host/0B_L3W8DD67iAVUktdHIxN0RnUjA/"
banner-img-url:    "https://googledrive.com/host/0B_L3W8DD67iAVUktdHIxN0RnUjA/"

links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Tools
    url: /tools/
  - title: People
    url: /people/

projects:
  - title: Living with the Railroads
    url: living-with-railroads
  - title: Year of the Bay
    url: year-of-the-bay
  - title: Emotions of London
    url: emotions-of-london
