title:            Center for Spatial and Textual Analysis
tagline:          "CESTA"
description:      "The Center for Spatial and Textual Analysis is a lab at Stanford University."
# Site domain goes here. Leave localhost server or blank when working locally.
url:

# Owner/author information
owner:
  name:           Center for Spatial and Textual Analysis
  email:
  twitter:        "cesta"
  github:         "cesta"
  facebook:       "cesta"
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    ""

future:           true
lsi:              false
pygments:         true
markdown:         kramdown
# http://jekyllrb.com/docs/permalinks/
permalink:        /:year/:month/:day/:title/

# Internal pages/posts to include in top navigation
links:
  - title: People
    url: /people/
  - title: Labs &amp; Projects
    url: /labs-projects/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json"]
